name: cities-cif
channels:
  - conda-forge
dependencies:
  - python=3.10
  - earthengine-api=0.1.411
  - geocube=0.4.2
  - geopandas=0.14.4
  - xarray=2024.7.0
  - rioxarray=0.15.0
  - odc-stac=0.3.8
  - pystac-client=0.7.5
  - pytest=7.4.3
  - xarray-spatial=0.3.7
  - xee=0.0.15
  - utm=0.7.0
  - osmnx=1.9.0
  - dask[complete]=2023.11.0
  - matplotlib=3.8.2
  - jupyterlab=4.0.10
  - s3fs=2024.5.0
  - geemap=0.32.0
  - pip=23.3.1
  - boto3=1.34.124
  - cdsapi=0.7.3
  - timezonefinder=6.5.2
  - scikit-image=0.24.0
  - exactextract=0.2.0
  - pip:
      - overturemaps==0.6.0
