name: cities-cif
channels:
  - conda-forge
dependencies:
  - python=3.10.16
  - boto3=1.37.1
  - cdsapi=0.7.5
  - cfgrib=0.9.15.0
  - dask[complete]>=2025.5.0
  - earthengine-api=1.5.9
  - exactextract=0.2.1
  - gdal=3.10.2
  - geemap=0.35.3
  - geocube=0.7.1
  - geopandas=1.0.1
  - ipython=8.34.0
  - jupyterlab=4.3.6
  - matplotlib=3.10.1
  - numpy=1.26.4
  - odc-stac=0.4.0
  - osmnx=2.0.2
  - overturemaps=0.14.0
  - pip=25.0.1
  - pystac-client=0.8.6
  - pytest=8.3.5
  - rioxarray=0.18.2
  - s3fs=2025.3.2
  - scikit-image=0.25.2
  - scipy=1.15.2
  - timeout-decorator #?
  - timezonefinder=6.5.9
  - utm=0.7.0
  - xarray=2025.3.1
  - xarray-spatial=0.4.0
  - xee=0.0.20

