name: cities-cif
channels:
  - conda-forge
dependencies:
  - python=3.10
  - earthengine-api=0.1.379
  - geocube=0.4.2
  - geopandas=0.14.1
  - rioxarray=0.15.0
  - odc-stac=0.3.8
  - pystac-client=0.7.5
  - pytest=7.4.3
  - xarray-spatial=0.3.7
  - xee=0.0.3
  - utm=0.7.0
  - osmnx=1.8.1
  - dask[complete]=2023.11.0
  - matplotlib=3.8.2
  - jupyterlab=4.0.10
  - s3fs=2024.5.0
  - geemap=0.32.0
  - pip=23.3.1
  - boto3=1.34.124
  - scikit-learn=1.5.0
  - cdsapi=0.7.0
  - pytz=2024.1
  - timezonefinder=6.5.2
  - pip:
      - git+https://github.com/isciences/exactextract
      - overturemaps==0.6.0
